### ISSUE TITLE
Support for *EventSource syntax to Enable ETW provider

### ISSUE THREAD

**Issue by MagicAndre1981** [smourier/TraceSpy#1]
[Perfview](https://github.com/Microsoft/perfview) and the last [Windows Performance Recorder](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-recorder) support the syntax *EventSource to enable an ETW provieder which is based on [Eventsource](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource).

Is it possible to also allow this syntax to start capturing such Eventsource providers?

**Comment by smourier** [comment]
TraceSpy is not meant for generic ETW sources. Only the one wich send strings.
