### ISSUE TITLE
Black theme?

### ISSUE THREAD

**Issue by magebot1** [smourier/TraceSpy#13]
Hello, thank you for such an amazing tool!

When sending a lot of data constantly, DebugView freezes on my machine while TraceSpy doesn't 👍 

Would be nice if it could have a black theme option!
An option to change the background and font color could help on this 🙏

**Comment by smourier** [comment]
Hi,

Thanks,

I don't currently have the time to do it. If you have ideas or code, you can make pull request :-)

Simon.

**Comment by smourier** [comment]
Closed due to inactivity.
