### ISSUE TITLE
Unicode symbols not displayed

### ISSUE THREAD

**Issue by eugenesvk** [smourier/TraceSpy#16]
Instead I get garbage like this even though I've changed the font the fonts support the symbols
<img width="63" alt="tracespy" src="https://github.com/smourier/TraceSpy/assets/12956286/65f0b3e2-fa1f-4898-8d82-51b1366466e7">

**Comment by smourier** [comment]
I suppose you're speaking about OutputDebugString ("ODS") traces as it should work fine for ETW traces.

Indeed, it didn't work as Unicode support for OutputDebugString is very limited as explained in official documentation: https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw

> OutputDebugStringW converts the specified string based on the current system locale information and passes it to OutputDebugStringA to be displayed. As a result, some Unicode characters may not be displayed correctly.

However, I've added a feature where you can choose the encoding used for ODS traces, and this can ultimately allow you to use Unicode strings, but only with some limitations:

* you must use UTF-8 encoding when you call OutputDebugStringA
* you must not use OutputDebugStringW at all
* you must configure WpfTraceSpy to use UTF-8 as the "ODS encoding"

See full details here
https://github.com/smourier/TraceSpy?tab=readme-ov-file#unicode-support-for-outputdebugstring-ods-traces

**Comment by eugenesvk** [comment]
Yes, this is about OutputDebugString 
Interesting, if these are global limitations, then why does those symbols show fine even in the old Debugview app?

Anyway, the newer version works (it had utf-8 already configured and I don't control which API the app calls as it's an external app AutoHotkey, but I guess the correct one), though some combining chars still bug

this is TraceSpy
<img width="36" alt="dbg1" src="https://github.com/smourier/TraceSpy/assets/12956286/8225532f-de57-4f1a-8589-05f4eb947321">

This is Debugview, layout is still buggy, but the combining chars are visible
<img width="27" alt="dbg2" src="https://github.com/smourier/TraceSpy/assets/12956286/41f8960d-46cf-450f-8cce-1c175fa04df6">


Thanks for a quick fix!

**Comment by smourier** [comment]
I don't know what app you're talking about exactly but this https://learn.microsoft.com/en-us/sysinternals/downloads/debugview doesn't work with Unicode.

If you don't control the app and it's using OutputDebugStringW then there's nothing to do, it won't work in the general case.

You should put exact input as texts, not bitmaps, they are useless when talking about characters.

**Comment by eugenesvk** [comment]
Yes, Debugview you linked to  is the app I meant, and it does work with unicode, that's where the screenshot is from (the text coming from the app is h⃣k⃣⌂)

The other app I've tried is https://github.com/CobaltFusion/DebugViewPP, which also displays the chars like DebugView

**Comment by smourier** [comment]
AFAIK none of these work correctly with Unicode in general (and UTF-16 encoding in particular), they don't work for me. Give me a text and I'll show you how they render on my machine.

Maybe you mean UTF-8, that's not strictly the same thing as Unicode and not the same thing as UTF-16, maybe what happens is you're using a code page on your machine which make it work, like I said in the doc here https://github.com/smourier/TraceSpy?tab=readme-ov-file#unicode-support-for-outputdebugstring-ods-traces that is possible

**Comment by eugenesvk** [comment]
I've given you the text in the previous comment: h⃣k⃣⌂

I don't know the exact encoding paths, the file with this text is UTF-8, but AutoHotkey is a UTF-16 app, the code page on my machine is indeed UTF-8, and that's the setting in TraceSpy (guess it picked up the system version, I didn't change anything)

**Comment by smourier** [comment]
This is how this text shows up:

![Screenshot 2024-03-06 145454](https://github.com/smourier/TraceSpy/assets/5328574/6cee93d9-e513-4e1b-af58-ce6a65e484b4)
![Screenshot 2024-03-06 145348](https://github.com/smourier/TraceSpy/assets/5328574/2d08278d-0df7-4420-b455-72bea1a4dc76)

But I'm not sure about the text you give, this is how it looks in my Chrome looking at this question:

![image](https://github.com/smourier/TraceSpy/assets/5328574/abd025ab-94b2-4532-8b4d-c1e90466f5bc)

In Notepad (Windows 11)

![image](https://github.com/smourier/TraceSpy/assets/5328574/2d00161a-57ed-4ae1-acc7-cd7035fc893b)

In Visual Studio

![image](https://github.com/smourier/TraceSpy/assets/5328574/a91bfb50-7b05-4088-9558-187178b4eefc)

In Visual Studio Code

![image](https://github.com/smourier/TraceSpy/assets/5328574/630d0efc-6522-4c8c-9ebc-cd17bb27728f)



If you can provide me a way to test it with autohotkey, I can have a deeper look.

**Comment by eugenesvk** [comment]
DebugView++ is the same as DebugView here,

<img width="143" alt="DBGVpp" src="https://github.com/smourier/TraceSpy/assets/12956286/aa1ace0d-37a4-4085-9306-d33243d19145">

Maybe it's a font issue? Though tried different fonts, they dispaly it fine, but this could also be some font fallback system thing?

The Chrome/Notepad are semi-fine, wouldn't expect any heroics from these apps, but they do display the combining keycap around the key, which is close to the proper way

The AutoHotkey test is as simple as this `script.ahk` example file below:
```ahk
#Requires AutoHotKey 2.0

!1::OutputDebug('⎇1OutputDebug: h⃣k⃣⌂')
```
every time you press <kbd>Alt</kbd><kbd>1</kbd> after launching this script you should get the message `⎇1OutputDebug: h⃣k⃣⌂` ODS-printed
(I think AutoHotkey might still have two modes of installation: ANSI and Unicode ones, I was using the latter)

**Comment by smourier** [comment]
So the text here h⃣k⃣⌂ is composed of 5 unicode codepoints

0x0068 h
0x20E3 "Combining Enclosing Keycap" https://www.compart.com/en/unicode/U+20E3
0x006B k
0x20E3 "Combining Enclosing Keycap"
0x2302 "House" https://www.compart.com/en/unicode/U+2302

Indeed when we see question mark glyphs (in a box or w/o a box), it means the font (or the graphics layer) used doesn't handle the caracter so this rendered text:

![image](https://github.com/smourier/TraceSpy/assets/5328574/a5251f68-a97e-421b-931c-d2d056e6eb5f)
means the font isn't capable of displaying all the corresponding glyphs.

If I use, say, unifont https://www.unifoundry.com/unifont/index.html I can have glyph displayed when I do as instructed, ie: UTF8 + OutputDebugStringA

So, with this C# program:

```
 static void Main()
 {
     var str = "h⃣k⃣⌂";
     Trace.WriteLine(str);

     // one way of using it
     OutputDebugStringA(str);

     // another way of using it (if UnmanagedType.LPUTF8Str is not available)
     var bytes = Encoding.UTF8.GetBytes(str);
     OutputDebugStringA(bytes);
 }

 [DllImport("kernel32")]
 private static extern void OutputDebugStringA(byte[] str);

 [DllImport("kernel32")]
 private static extern void OutputDebugStringA([MarshalAs(UnmanagedType.LPUTF8Str)] string str);

```

This is what I see:

![image](https://github.com/smourier/TraceSpy/assets/5328574/06b078fc-58a1-42a0-bd07-e041cd83c50a)

I can't manage to have this displayed using DbgView or DebugView++, if you see the proper glyphs w/o using a specific font, then it's something installed or configured in your machine lilke regional settings etc. that make it work. Actually this discussion in DebugView++ issues is more or less the same https://github.com/CobaltFusion/DebugViewPP/issues/389

As for authotkey I don't know how to do the strict technical equivalent of what's done in C# (or in C/C++), ie OutputDebugStringA+UTF8.

So, I will leave the code as is.
PS: noone should use OutputDebugString, it's a 30+ year piece of crap.

**Comment by eugenesvk** [comment]
> if you see the proper glyphs w/o using a specific font, then it's something installed or configured in your machine lilke regional settings etc. that make it work.

Checked in an app that Tahoma system font has this symbol, and it indeed is also working in TraceSpy! Is TraceSpy maybe doing something special regarding font fallbacks compared to the DebugViewPP?

Or maybe it's indeed that setting (I have it enabled) ![image](https://private-user-images.githubusercontent.com/9715604/274873918-7efe6054-2098-4cb3-bed6-3c15ed7873e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDMyOTAsIm5iZiI6MTcwOTgwMjk5MCwicGF0aCI6Ii85NzE1NjA0LzI3NDg3MzkxOC03ZWZlNjA1NC0yMDk4LTRjYjMtYmVkNi0zYzE1ZWQ3ODczZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDkxNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjExODdjODVhNGQ2MmM3N2U3MGZkOWU2OTJjMjU5Mjk3NTZiMWY2NWU4OTA1NTc5YmY1NmYwZjcxY2VhYWExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vzpg-oq7uXx8H2yRHZwsKWbtiYj91Wjb0xoF-kNTnGY)


but then again the question is why is this same setting not working for TraceSpy, but working for DebugViewPP?

**Comment by smourier** [comment]
I don't know, but actually it's the reverse for me, I can't get DebugView++ to display the proper glyph whatever I try.

**Comment by eugenesvk** [comment]
Have you tried setting those utf-8 system settings? Just checked, and indeed, without this enabled I get `???`instead in degubview.

So I guess that explains it - TraceSpy is using a different path from this utf-8 system setting and thus doesn't have access to the system font fallback mechanism that is used automatically in that system setting path?

**Comment by smourier** [comment]
With UTF-8 as default in Windows, WpfTraceSpy will choose UTF-8 as default encoding instead of ANSI encoding (this one depends on the code page) so with the same C# program, we see the glyph displayed but the 0x20E3 are not *combined* (this is more a limitation of WPF I think).

![image](https://github.com/smourier/TraceSpy/assets/5328574/3b091de3-ac9a-44ae-9099-7bfedf0c78a8)

So Unicode support works (rendering is another thing). For example if I send these chinese characters "我们一起去玩吧。" (with same C# code and Lucida Console) I see this, which is correct

![image](https://github.com/smourier/TraceSpy/assets/5328574/fe5fc2d8-b172-427b-b282-081850ea3281)

**Comment by eugenesvk** [comment]
Are you sure the first screenshot is not blank boxes signifying the char is not found instead of combining keycap? Maybe check with another combining char like ̥
U+032

Here (output from autohotkey) I see that the ring char is displayed and combined while the keycap is not displayed and, naturally, not combined

<img width="52" alt="trace1" src="https://github.com/smourier/TraceSpy/assets/12956286/8ef60ae9-3dbc-408f-9d0c-b4987fe7d26f">

**Comment by smourier** [comment]
Is fixed for me.

**Comment by yg-i** [comment]
FWIW this worked great on my machine:

> you configure WpfTraceSpy to use UTF-8 as the "ODS encoding", like shown here (menu "Options"/"ODS Encoding...", by default the encoding is the default ANSI encoding):

![image](https://github.com/smourier/TraceSpy/assets/148152939/de65ce8f-26fb-46b3-97df-17ea61964b15)

**Comment by eugenesvk** [comment]
> FWIW this worked great on my machine:

have you tried the combining keycap char?

**Comment by yg-i** [comment]
Here's how it looks with Tahoma font (I assume this is the appearance you want).[1] FWIW, I'm pretty convinced this is not an encoding but a font issue. If I copy and paste your `h⃣k⃣⌂ ` into Microsoft Word, and try various different fonts, I find that pretty much every font displays this differently, and only Tahoma produces your desired appearance. Even in Chrome and Firefox, without forcing the Tahoma font, they look all tangled up, like in [2].

[1]
![image](https://github.com/smourier/TraceSpy/assets/148152939/1bd58d4a-e776-45cb-9fe7-6ae4379e47fa)

[2] 
![image](https://github.com/smourier/TraceSpy/assets/148152939/d238cb7b-2c15-4d5d-a5e5-430e33901e6f)

**Comment by eugenesvk** [comment]
> Here's how it looks with Tahoma font (I assume this is the appearance you want).[1]

No, try it **without** the Tahoma font manually selected. It should work without users explicitly selecting the font as it does on DebugView++ and Word and all the other apps - they use system font fallback to display these symbols in the font that has them even if the currently selected font doesn't have them

↓ this is without Tahoma selected, the base font is a different, monospaced font
<img width="143" alt="DBGVpp" src="https://github.com/smourier/TraceSpy/assets/12956286/aa1ace0d-37a4-4085-9306-d33243d19145">

> FWIW, I'm pretty convinced this is not an encoding but a font issue

It is and has been noted above, "Checked in an app that Tahoma system font has this symbol, and it indeed is also working in TraceSpy! Is TraceSpy maybe doing something special regarding font fallbacks compared to the DebugViewPP?"

But it's still not "working great" since font fallback is NOT working

**Comment by yg-i** [comment]
> It should work without users explicitly selecting the font as it does on DebugView++ and Word and all the other apps

It doesn't work in Microsoft Word (or Chrome, or Firefox) on my machine without using Tahoma font.

![image](https://github.com/smourier/TraceSpy/assets/148152939/5255045a-b241-48b4-a153-38c625f93a6f)

If you run `Get-Culture` in powershell, do you have `en-US` as the output? If you have a different locale, font fallback behavior could be different (see https://github.com/electron/electron/issues/18829 for some discussion) and it could also explain why dgbview/DebugView++ can display unicode correctly on your machine (owing to the locale sensitivity of OutputDebugStringW @smourier pointed to earlier)

**Comment by eugenesvk** [comment]
What do you mean "it doesn't work" when in the "Verdana"-labeled text you have the same **working** thing - a combining keycap correctly displayed as a combining keycap (though not perfectly overlapping the `h` key)?

(by the way, you can actually click after `h` and check the font in Word- you'll see that it's not Verdana anymore, but Tahoma, font substitution silently works)

> If you run Get-Culture in powershell, do you have en-US as the output? 

yes

> and it could also explain why dgbview/DebugView++ can display unicode correctly on your machine

No, you linked to a different issue. In that case the font sub was working, just using the wrong font, but still a font with a valid glyph for this symbol. In this case the font with a valid glyph exists, but is NOT used, instead displaying a generic "not found" box
