### ISSUE TITLE
Search doesn't find text that is at the beginning of a line

### ISSUE THREAD

**Issue by riQQ** [smourier/TraceSpy#17]
**Steps to reproduce**
- have a program print a text starting with `building` via ODS
- use the search and search for `building`
- a dialog is shown stating that nothing was found

![screenshot of dialog](https://github.com/smourier/TraceSpy/assets/3404787/40d117a0-3232-4f6a-ae5a-b230acf84e39)

**Expected**
Search also finds text at the beginning of a line.

**Version**
WpfTraceSpy.exe 4.1.1.0 from GitHub releases

**Comment by smourier** [comment]
It seems to be working for me:

![image](https://github.com/smourier/TraceSpy/assets/5328574/14468728-d882-451e-8125-043df2893b1d)

With this colorizer:

![image](https://github.com/smourier/TraceSpy/assets/5328574/00fc5906-55ef-4011-a549-70318948376d)

**Comment by riQQ** [comment]
Sorry, my report was imprecise. I thought it was related to colorizers, but it is actually related to the searched text being at the start of the log message.

**Comment by smourier** [comment]
Thanks, should be fixed now.

**Comment by riQQ** [comment]
Confirmed fixed with 4.2.0.0, thanks.
