### ISSUE TITLE
IMFVirtualCamera::Start fails on WinArm64

### ISSUE THREAD

**Issue by ghochman-private** [smourier/TraceSpy#18]
Hi @smourier 

Thank you for this insightfull code sample!

I tried to build and run in on Windows11/Arm64 (Win11 Pro 10.0.26073). While I could build it successfully with VS 2022 CE - I failed to run it. IMFVirtualCamera::Start call returns  "Access is denied" code (see the attached log).

Any thoughts on what am I missing here?

Thanks in advance,
Gershon.

[winarm64.log](https://github.com/user-attachments/files/15751400/winarm64.log)

**Comment by smourier** [comment]
You're targeting the wrong repo, this is TraceSpy, please delete and repost in the right repo.

PS: you're probably hiting this issue https://github.com/smourier/VCamSample/issues/1#issuecomment-2057243344

**Comment by ghochman-private** [comment]
Thanks for fast reply. Will do.

**Comment by ghochman-private** [comment]
Wrong project.
