### ISSUE TITLE
How to use it in .net core 2.0 ?

### ISSUE THREAD

**Issue by glat** [smourier/TraceSpy#5]

**Comment by smourier** [comment]
For the client side, Trace.Writeline is supposed to work on .net core 2.0, doesn't it? Otherwise .NET core doesn't support EventProvided AFAIK, so you can't use ETW here

**Comment by glat** [comment]
I understand. I used TraceSpy to debug web applications allowing me to see both browser and debug window on the screen. In asp.net core 2.0 I lost this.
