### ISSUE TITLE
Remote connect feature

### ISSUE THREAD

**Issue by edenprairie** [smourier/TraceSpy#6]
Could you consider remote connect feature? This is very common use case in real enterprise project. We need to aggregate all trace from multiple servers.

**Comment by smourier** [comment]
Hi,

Yes, I have started that quite a few years ago, the project is still here: https://github.com/smourier/TraceSpy/tree/master/TraceSpyService but I have not spend time on any and it's far from being complete. Actually, if I started it today, I'll probably use something like websockets.

**Comment by smourier** [comment]
I won't have the time to update TraceSpyService. I have deprecated the project and removed it from main solution.
