### ISSUE TITLE
Inclusion filter

### ISSUE THREAD

**Issue by ero-qt** [smourier/TraceSpy#7]
I use TraceSpy to view debug output from one process and one process alone. For something like this, the list of exclusion filters quickly becomes many dozen entries long. Would it be possible to incorporate a sort of "inclusion filter" instead, where only ODS traces from specified processes (by name, of course) are displayed?

**Comment by smourier** [comment]
Hi,

ODS is really a thing of the past.

If you own the process, the easiest is to replace your OutputDebugString code by using ETW traces https://github.com/smourier/TraceSpy#etw-messages-support. This is much much faster in the client & in trace spy and then you can filter on the ETW provider guid so you will get only traces corresponding to this guid.

**Comment by ero-qt** [comment]
I do not own the process.  

The software I'm monitoring is LiveSplit, a speedrun timer for which one can create scripts for individual games, reading memory and executing different methods accordingly.  

LiveSplit was started quite long ago, so I can understand the use of ODS traces for debugging these custom scripts.  

I use TraceSpy to debug only this one program's debug prints.

**Comment by ero-qt** [comment]
Inverse matching.  

`^((?!LiveSplit).)*$`
