### ISSUE TITLE
Contribution: Office 32- and 64-bit VBA compatibility for ETW

### ISSUE THREAD

**Issue by SystemsModelling** [smourier/TraceSpy#8]
ETW 26us in VBA is three times the speed  of OutputDebugString 77us.
And it correctly displays Unicode strings like Cyrillic.
I'd like to contribute a module ETWModule3264.bas that handles both current versions of VBA.
This has been tested in 32-bit Excel 365 and 64-bit Excel 365 on Windows 10.
 I work only in Excel, but it should apply to other Office products too.
[ETWModule3264.bas.txt](https://github.com/smourier/TraceSpy/files/7046157/ETWModule3264.bas.txt)

**Comment by smourier** [comment]
Thanks! I've added it to the vba directory.

**Comment by SystemsModelling** [comment]
Thanks Simon. It would be nice to have File>Save, it's a bit slow to copy & paste 2M lines into Notepad++ :)

Edit: I can do it by Copy from Tracespy then in Powershell do
Get-Clipboard > tracelog.txt
