### ISSUE TITLE
Crash when using Copy commands

### ISSUE THREAD

**Issue by softexpert** [smourier/TraceSpy#9]
Hello,

WpfTraceSpy crashes if I use "Copy Text" or "Copy Full Line" commands.
I ran it even as local Administrator, it did not change anything.

To reproduce:
1. Launch WpfTraceSpy
2. Use "Send Test Trace" and type a few letters (just to have a line in the grid)
3. When the line is displayed in the grid, try to copy with "Copy Text" or with "Copy Full Line"
WpfTraceSpy crashes.

Going to the code, It occurs on the `System.Windows.Clipboard.SetText(sb.ToString())` line.
Apparently it is a long ilness ( [see this](https://social.microsoft.com/Forums/en-US/d2a67962-ca82-43f2-8476-213ccbdbdd92/clipboardsettext-exception) )

It can be mitigated by wrapping into a **try** ... **catch** block, like this:
```csharp
        private void CopyFullLine_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var sb = new StringBuilder();
                foreach (var evt in LV.SelectedItems.OfType<TraceEvent>().OrderBy(evt => evt.Index))
                {
                    sb.AppendLine(evt.FullText);
                }
                System.Windows.Clipboard.SetText(sb.ToString(), System.Windows.TextDataFormat.Text);            
            }
            catch { }
        }
```
Hope this helps ...

Best regards,
SoftExpert

**Comment by smourier** [comment]
Hi,

I don't reproduce any error. And actually, the code is `System.Windows.Clipboard.SetText(sb.ToString())` without any other argument.

Are you building it or running from the release? What is the exception and the full stack trace?

**Comment by softexpert** [comment]
Hi,

I ran it first from the releases - the 4.0.3 version.
Then, being curious, I downloaded the code and built it on my VM.
I encountered the issue on 2 different servers (Windows 2019) hosted in VMWare or VirtualBox.
My guess is that the clipboard is held busy and the `System.Windows.Clipboard.SetText(sb.ToString())` call will raise an exception in that case.
Are you testing it on a non-server Windows ?

**Comment by softexpert** [comment]
Ah, and more details: running it in Debug mode from VisualStudio will not raise the issue.
Here is a screenshot where we can see the exception trapped and the code (having or not the extra parameter does not change anything).
![image](https://user-images.githubusercontent.com/1254018/135496961-bc3b9802-215b-448b-abc4-8ce9936f5607.png)

**Comment by smourier** [comment]
As I said, I can't reproduce, in debug, release, admin, non admin, x86, x64, etc. Maybe this is due to a virtual environment.

Anyway, I've added some code to avoid possible errors like that.

**Comment by softexpert** [comment]
Well, thank you for the quick fix !

**Comment by softexpert** [comment]
For general information, .NET, WPF and the Clipboard might have issues (.NET upto 4.8, don't know about latest versions 5+) - this [StackOverflow article](https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid) gives a number of approaches.
